import Foundation
import Testing
@testable import Newswire

struct TickerScannerTests {
    @Test func findsSpelledOutSymbols() {
        #expect(TickerScanner.symbols(in: "Nu Holdings (NU) said it's not pursuing a transaction with Monzo.") == ["NU"])
        #expect(TickerScanner.symbols(in: "Micron Technology (NASDAQ:MU) and Nike (NYSE: NKE) rose; $TSLA fell.") == ["MU", "NKE", "TSLA"])
        #expect(TickerScanner.symbols(in: "Shares of Micron (MU.O) jumped.") == ["MU"])
        #expect(TickerScanner.symbols(in: "Shares of MGIC Investment Corporation ( MTG ), a private mortgage insurer, fell.") == ["MTG"])
    }

    @Test func skipsAcronymsAndPlainParentheses() {
        #expect(TickerScanner.symbols(in: "The chief executive (CEO) spoke about artificial intelligence (AI) and the (big) plan.").isEmpty)
        #expect(TickerScanner.symbols(in: "U.S. GDP rose, the Federal Reserve (FED) said.").isEmpty)
    }
}

struct ArticleContainerTests {
    @Test func readsOnlyThePublisherArticleContainer() {
        let html = """
        <p>Related: Another company's quarterly results beat expectations across every segment this quarter.</p>
        <div data-test-id="content-container"><p>phototechno/iStock via Getty Images</p>
        <p>Shares of MGIC Investment Corporation (MTG), a private mortgage insurance provider, retreated almost 9% on Wednesday, ending at $25.84.</p>
        <p>Peers across the private mortgage insurance space posted steep declines as well during the session.</p></div>
        <span data-test-id="content-container">This article was automatically generated by an AI tool.</span>
        """
        let result = ArticleExtractor.extract(html: html, baseURL: URL(string: "https://seekingalpha.com/news/1")!)
        #expect(result.targeted)
        #expect(result.paragraphs.count == 2)
        #expect(result.paragraphs.first?.hasPrefix("Shares of MGIC") == true)
    }
}

struct ArticleVideoTests {
    private let base = URL(string: "https://www.example.com/news/story")!

    @Test func findsPlayableVideoMetadata() {
        let html = #"<meta property="og:video:type" content="application/x-mpegURL"><meta property="og:video:secure_url" content="https://video.example.com/hls/master.m3u8">"#
        #expect(ArticleExtractor.video(in: html, relativeTo: base)?.absoluteString == "https://video.example.com/hls/master.m3u8")
    }

    @Test func findsYouTubeEmbedsAndIgnoresPlayerPages() {
        let html = #"<meta name="twitter:player" content="https://www.example.com/player.html"><iframe width="560" src="https://www.youtube.com/embed/dQw4w9WgXcQ?rel=0"></iframe>"#
        let video = ArticleExtractor.video(in: html, relativeTo: base)
        #expect(video.flatMap(ArticleExtractor.youtubeID) == "dQw4w9WgXcQ")
        #expect(ArticleExtractor.video(in: "<p>No video here.</p>", relativeTo: base) == nil)
    }
}

struct ArticleImageTests {
    @Test func picksTheImageNotItsDimensions() {
        let html = #"<meta property="og:image:width" content="1200"><meta property="og:image" content="https://i.example.com/photo.jpg?width=1200&amp;q=85">"#
        #expect(ArticleExtractor.metaImage(in: html, relativeTo: URL(string: "https://www.example.com/a/b")!)?.absoluteString == "https://i.example.com/photo.jpg?width=1200&q=85")
    }
}
